services:

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - 8015:8015
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: production
    container_name: ag-nebula-frontend

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8011:8011
    volumes:
      - ./app:/app
    container_name: ag-nebula-app

    environment:
      - NODE_ENV=production

  mongodb:
    image: mongo:latest
    ports:
      - 27019:27019
    volumes:
      - mongo_data:/data/db
    container_name: ag-nebula-mongodb


  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    ports:
      - 7005:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: ag-nebula-postgresql

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    container_name: ag-nebula-pgadmin

volumes:
  mongo_data:
  postgres_data: