import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const montserrat = localFont({
  src: '../app/fonts/MontserratVF.ttf',
  variable: '--font-montserrat',
});

const cabin = localFont({
  src: '../app/fonts/CabinVF.ttf',
  variable: '--font-cabin',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`dark ${montserrat.variable} ${cabin.variable} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}