import type { Metadata } from "next";
import { Montserrat, Cabin} from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"], variable: '--font-montserrat' });
const cabin = Cabin({ subsets: ["latin"], variable: '--font-cabin' });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${montserrat.variable} ${cabin.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
